repos:
  - repo: https://github.com/MarketSquare/robotframework-robocop
    rev: 5.1.0
    hooks:
    - id: robocop
      name: robocop
      entry: robocop -rules robocop.cfg
      files: '.*\.(robot|resource)$'
      language: python
      description: "RobotFramework source code linter"